// src/ui/components/github/GithubSummaryStatus.tsx
/** @jsxImportSource @emotion/react */
import { css } from '@emotion/react';
import { green, orange, red } from '@mui/material/colors';
import { GithubStatus } from '../../../domain/github/GithubStatus';
import { icons } from '../../../res/icons';

type GithubSummaryStatusProps = {
    status: GithubStatus;
};

export const GithubSummaryStatus: React.FC<GithubSummaryStatusProps> = ({ status }) => {
    return (
        <div css={styles.container}>
            <img css={styles.summaryStatusIcon} src={statusIcon[status.indicator]} />
            <h2 css={styles.description}>{status.description}</h2>
        </div>
    );
};

const styles = {
    container: css({
        height: 'auto',
        display: 'flex',
        flexDirection: 'row',
        backgroundColor: green[500],
        color: 'white',
        alignItems: 'center',
        margin: '26px 20px 40px',
        paddingLeft: '16px',
        borderRadius: '5px',
        minWidth: '40px'
    }),
    summaryStatusIcon: css({
        width: '40px',
        height: '40px'
    }),
    none: css({
        backgroundColor: green[600]
    }),
    minor: css({
        backgroundColor: green[300]
    }),
    major: css({
        backgroundColor: orange.A700
    }),
    critical: css({
        backgroundColor: red[900]
    }),
    description: css({
        margin: '14px 0px'
    })
};

const statusIcon = {
    none: icons.check,
    minor: icons.info,
    major: icons.attention,
    critical: icons.error
};

// src/components/github/GithubSummaryStatus.vue
<script setup lang="ts">
import type { GithubStatus } from '../../domain/github/GithubStatus'

defineProps<{
    status: GithubStatus
}>()
const icons = {
    none: 'mdi-check',
    minor: 'mdi-information-variant-circle-outline',
    major: 'mdi-alert-outline',
    critical: 'mdi-close-circle-outline'
}
</script>

<template>
    <div class="summary-container">
        <v-icon
            class="summary-icon"
            color="white"
            v-bind:icon="icons[status.indicator]"
            size="30"
        />
        <h2>{{ status.description }}</h2>
    </div>
</template>

<style scoped>
.summary-container {
    height: auto;
    display: flex;
    flex-direction: 'row';
    background-color: #28a745;
    color: white;
    align-items: center;
    margin: 16px 24px;
    padding: 10px 0px 10px 16px;
    border-radius: 6px;
}
.summary-icon {
    margin-right: 10px;
}
</style>
